@extends('layout.app')

@section('content')

<div class="content">
  <div class="card mb-3">
    <div class="card-body">

        <form method="GET"
              action="{{ route('supervisor.student.performance.report') }}">

            <div class="row">

                <div class="col-md-8">
                    <label>Select Class</label>

                    <select name="class_id"
                            class="form-control"
                            required>

                        <option value="">
                            -- Select Class --
                        </option>

                        @foreach($classes as $class)

                            <option value="{{ $class->id }}"
                                {{ request('class_id') == $class->id ? 'selected' : '' }}>

                                {{ $class->class_name }}

                            </option>

                        @endforeach

                    </select>
                </div>

                <div class="col-md-4 mt-4">

                    <button type="submit"
                            class="btn btn-primary">

                        Generate Report

                    </button>

                </div>

            </div>

        </form>

    </div>
</div>
@if(request('class_id'))
    <div class="card shadow">

        <div class="card-header bg-primary text-white">
            <h4>STUDENT PERFORMANCE REPORT</h4>
        </div>

        <div class="card-body">

            <p><strong>School:</strong> {{ $school->name }}</p>
            <p><strong>Date:</strong> {{ date('d M Y') }}</p>
            <p><strong>Generated By:</strong> Supervisor</p>

            <hr>

            <h5>Summary</h5>

            <table class="table table-bordered">

                <tr>
                    <th>Total Students</th>
                    <td>{{ $students }}</td>
                </tr>

                <tr>
                    <th>Passed</th>
                    <td>{{ $passed }}</td>
                </tr>

                <tr>
                    <th>Failed</th>
                    <td>{{ $failed }}</td>
                </tr>

                <tr>
                    <th>Pass Rate</th>
                    <td>{{ $passRate }}%</td>
                </tr>

                <tr>
                    <th>Average Score</th>
                    <td>{{ $averageScore }}%</td>
                </tr>

            </table>

            <h5 class="mt-4">Subject Performance</h5>

            <table class="table table-striped">

                <thead>
                    <tr>
                        <th>Subject</th>
                        <th>Students</th>
                        <th>Average</th>
                        <th>Pass Rate</th>
                    </tr>
                </thead>

                <tbody>

                @foreach($subjectPerformance as $subject)

                    <tr>
                        <td>{{ $subject->subject_name }}</td>
                        <td>{{ $subject->students }}</td>
                        <td>{{ number_format($subject->average,2) }}%</td>
                        <td>{{ $subject->pass_rate }}%</td>
                    </tr>

                @endforeach

                </tbody>

            </table>

            <h5 class="mt-4">Top 10 Students</h5>

            <table class="table table-success">

                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Student Name</th>
                        <th>Average</th>
                    </tr>
                </thead>

                <tbody>

                @foreach($topStudents as $student)

                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>
                            {{ $student->firstname }}
                            {{ $student->lastname }}
                        </td>
                        <td>
                            {{ number_format($student->average_score,2) }}%
                        </td>
                    </tr>

                @endforeach

                </tbody>

            </table>

            <h5 class="mt-4">Bottom 10 Students</h5>

            <table class="table table-danger">

                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Student Name</th>
                        <th>Average</th>
                    </tr>
                </thead>

                <tbody>

                @foreach($bottomStudents as $student)

                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>
                            {{ $student->firstname }}
                            {{ $student->lastname }}
                        </td>
                        <td>
                            {{ number_format($student->average_score,2) }}%
                        </td>
                    </tr>

                @endforeach

                </tbody>

            </table>

            <div class="mt-5">

                <h5>Supervisor Comments</h5>

                <div class="alert alert-info">

                    Ufaulu wa jumla ni
                    {{ $averageScore }}%.

                    @if($averageScore >= 70)

                        Wanafunzi wanafanya vizuri.
                        Endeleeni kusimamia ubora wa elimu.

                    @elseif($averageScore >= 50)

                        Ufaulu ni wa wastani.
                        Inashauriwa kuongeza ufuatiliaji wa masomo
                        yenye ufaulu mdogo.

                    @else

                        Ufaulu ni mdogo.
                        Inashauriwa kuwepo remedial classes
                        na ukaguzi wa karibu wa walimu.

                    @endif

                </div>

            </div>

        </div>

    </div>
    <form action="{{ route('report.send') }}" method="POST" class="mt-3">
    @csrf
    <input type="hidden" name="class_id" value="{{ request('class_id') }}">
    <input type="hidden" name="school_id" value="{{ $school->id }}">
    <input type="hidden" name="average_score" value="{{ $averageScore }}">
    <input type="hidden" name="pass_rate" value="{{ $passRate }}">
    <input type="hidden" name="students" value="{{ $students }}">
    <input type="hidden" name="passed" value="{{ $passed }}">
    <input type="hidden" name="failed" value="{{ $failed }}">
    
    <input type="hidden" name="comments" value="Ufaulu wa jumla ni {{ $averageScore }}%.">

    <button type="submit" class="btn btn-success">
        Send Report To Admin
    </button>
</form>
@endif
    

</div>

@endsection